// <auto-generated />
using System;
using MagicVilla_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240208165032_SeedVillaTableWithDates")]
    partial class SeedVillaTableWithDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_WebAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SqFt")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 2, 8, 21, 50, 32, 133, DateTimeKind.Local).AddTicks(6650),
                            Details = "aasdf asd  asdf asdf",
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 500.0,
                            SqFt = 550,
                            UpdatedDate = new DateTime(2024, 2, 8, 21, 50, 32, 133, DateTimeKind.Local).AddTicks(6663)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 2, 8, 21, 50, 32, 133, DateTimeKind.Local).AddTicks(6666),
                            Details = "aasdf asd  asdf asdf",
                            ImageUrl = "",
                            Name = "Royal Villa 2",
                            Occupancy = 5,
                            Rate = 500.0,
                            SqFt = 550,
                            UpdatedDate = new DateTime(2024, 2, 8, 21, 50, 32, 133, DateTimeKind.Local).AddTicks(6666)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 2, 8, 21, 50, 32, 133, DateTimeKind.Local).AddTicks(6668),
                            Details = "aasdf asd  asdf asdf",
                            ImageUrl = "",
                            Name = "Royal Villa 3",
                            Occupancy = 5,
                            Rate = 500.0,
                            SqFt = 550,
                            UpdatedDate = new DateTime(2024, 2, 8, 21, 50, 32, 133, DateTimeKind.Local).AddTicks(6669)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
